version: "3"
services:
 nginx:
  ports:
   - "4000:80"
 node-app:
  build:
   context: .
   args: 
    NODE_ENV: development
  env_file:
   - ./config/.env
  volumes:
   - ./:/app
   - /app/node_modules
  command: npm run dev

 
   