version: "3"
services:
 nginx:
  image: nginx:stable-alpine
  ports:
   - "4000:80"
  volumes:
   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
 node-app:
  build: .
  image: srdjankljajo/node-app
  env_file:
   - ./config/.env

 mongo:
  image: mongo
  volumes:
   - mongo-db:/data/db
  env_file:
   - ./config/.env

volumes:
 mongo-db: